name: CI Testing Pipeline
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  # Allow manual triggers from the GitHub UI
  workflow_dispatch:

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        service: [auth, todo]
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: |
          cd ${{ matrix.service }}
          npm install
          
      - name: Run tests
        run: |
          cd ${{ matrix.service }}
          npm test
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET || 'test-jwt-secret' }}
